export const LISTEN_BUG_DESCRIPTION = 'LISTEN_BUG_DESCRIPTION';
export const LISTEN_BUG_DESCRIPTION_FAIL = 'LISTEN_BUG_DESCRIPTION_FAIL';
export const UNLISTEN_BUG_DESCRIPTION = 'UNLISTEN_BUG_DESCRIPTION';